//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Editor.rc
//
#define ID_INDICADOR_DES                1
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_CHILDFRAME                  129
#define IDR_MENUTEXT                    129
#define IDD_MACROPROP                   132
#define IDR_TEXTO                       133
#define IDD_TEXTO                       133
#define IDR_ACCELERATOR1                136
#define ID_ARCHIVO_ABRIR                138
#define ID_ARCHIVO_NUEVO                139
#define ID_AYUDA_SOBRE                  140
#define IDD_DIALOG1                     142
#define IDD_JOYPROP                     142
#define ID__                            144
#define ID__0                           145
#define IDR_MENUGRAF                    147
#define ID_PLANTILLAS                   148
#define ID_EDICI_REHACER                149
#define IDM_TEXTO                       150
#define IDM_GRAFICO                     151
#define IDS_TECLAS                      1000
#define IDB_TP                          1001
#define IDB_TS                          1002
#define IDC_CODIGOS                     1003
#define IDC_TAB1                        1004
#define IDC_RICHEDIT21                  1005
#define IDC_RICHEDIT22                  1006
#define IDS_RATON                       1007
#define IDB_R10                         1008
#define IDB_R11                         1009
#define IDB_R31                         1010
#define IDB_RL                          1011
#define IDB_RR                          1012
#define IDB_RU                          1013
#define IDB_RD                          1014
#define IDC_RS                          1015
#define IDC_R                           1016
#define IDB_RH                          1017
#define IDB_RN                          1018
#define IDB_RF                          1019
#define IDB_RI                          1020
#define IDC_REPS                        1021
#define IDC_REP                         1022
#define IDB_MP0                         1023
#define IDB_MP1                         1024
#define IDB_M10                         1025
#define IDB_M20                         1026
#define IDB_M30                         1027
#define IDB_M11                         1028
#define IDB_M21                         1029
#define IDB_M22                         1030
#define IDB_P                           1031
#define IDC_P                           1032
#define IDC_PS                          1033
#define IDS_REPETIR                     1034
#define IDS_PAUSA                       1035
#define IDS_MODOS                       1036
#define IDB_R20                         1037
#define IDB_R30                         1038
#define IDB_R21                         1039
#define IDS_JMACROS                     1040
#define IDC_JMACROS                     1041
#define IDB_JMACROS                     1042
#define IDS_JELEMENTOS                  1043
#define IDB_JELEMENTOS                  1044
#define IDB_JR                          1045
#define IDB_JP                          1046
#define IDC_JELEMENTOS                  1047
#define IDS_JMODISC                     1048
#define IDB_JK0                         1049
#define IDJ_K1                          1050
#define IDB_JK1                         1050
#define IDB_JM1                         1051
#define IDB_JM2                         1052
#define IDB_JM3                         1053
#define IDB_JX1                         1054
#define IDB_JX2                         1055
#define IDB_JX3                         1056
#define IDS_MODISB                      1057
#define IDS_JMODISB                     1057
#define IDB_JDX1                        1058
#define IDC_JDX1                        1059
#define IDC_JSDX1                       1060
#define IDS_JDXBTN                      1061
#define IDB_JDX2                        1062
#define IDC_JDX2                        1063
#define IDC_JSDX2                       1064
#define IDC_JDX3                        1065
#define IDC_JSDX3                       1066
#define IDS_JDXSPOV                     1067
#define IDB_JT                          1068
#define IDC_JT                          1069
#define IDC_JST                         1070
#define IDB_JAS1                        1071
#define IDS_JMODISE                     1072
#define IDB_JAS2                        1073
#define IDB_JASX                        1074
#define IDB_JASY                        1075
#define IDB_JASZ                        1076
#define IDB_JASR                        1077
#define IDB_JASD                        1078
#define IDB_JINC                        1079
#define IDB_JDEC                        1080
#define IDC_JE1                         1081
#define IDC_JSE1                        1082
#define IDS_JBANDA                      1083
#define IDB_JB                          1084
#define IDC_EDIT6                       1085
#define IDC_JE2                         1085
#define IDC_JE3                         1086
#define IDC_JSE2                        1087
#define IDC_JSE3                        1088
#define ID_INDICADOR_LIN                2001
#define ID_INDICADOR_CAR                2002
#define ID_INDICADOR_SOB                2003
#define ID_INDICADOR_MAY                2004
#define ID_INDICADOR_NUM                2005
#define ID_BUTTON32774                  32774
#define ID_COMPILAR                     32774
#define ID_LANZAR                       32775

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        151
#define _APS_NEXT_COMMAND_VALUE         32776
#define _APS_NEXT_CONTROL_VALUE         1089
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
